services:
  web:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - DB_NAME=testdb
      - SESSION_SECRET=${SESSION_SECRET:-$(openssl rand -hex 32)}
      - NODE_ENV=production
      - FLAG=NETSOS{REDACTED}
      - ADMIN_PASSWORD=[REDACTED]
    volumes:
      - .:/app
    command: [ "npm", "run", "start" ]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
